name: Release Build

on:
  release:
    types: [published]

env:
  RBXL_FILE: MiastoX.rbxl
  PLACE_ID: ${{ vars.PLACE_ID }}
  UNIVERSE_ID: ${{ vars.GAME_ID }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wally Packages
        run: wally install

      - name: Generate Sourcemap
        run: rojo sourcemap test.project.json -o sourcemap.json

      - name: Export Wally Package Types
        run: wally-package-types --sourcemap sourcemap.json Packages

      - name: Luau LSP Analysis
        run: luau-lsp analyze --sourcemap sourcemap.json --definitions globalTypes.d.lua src tests

      - name: Build Game Place
        run: rojo build test.project.json -o ${{ env.RBXL_FILE }}

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.RBXL_FILE }}
          asset_name: ${{ env.RBXL_FILE }}
          tag: ${{ github.event.release.tag_name }}

      - name: Deploy to Roblox
        shell: pwsh
        run: |
          rbxcloud.exe experience publish `
            --filename ${{ env.RBXL_FILE }} `
            --place-id ${{ env.PLACE_ID }} `
            --universe-id ${{ env.UNIVERSE_ID }} `
            --version-type published `
            --api-key ${{ secrets.DEPLOY_API_KEY }}
