repos:
  - repo: local
    hooks:
      - id: stylua
        name: StyLua
        entry: stylua --check .
        language: system
        types: [lua, luau]
        pass_filenames: false

      - id: selene
        name: Selene
        entry: selene .
        language: system
        types: [lua, luau]
        pass_filenames: false

      - id: toml-validate
        name: TOML Validate
        entry: toml-validate
        language: system
        types: toml
        pass_filenames: false

      - id: trufflehog
        name: TruffleHog
        entry: trufflehog filesystem .
        language: system
        types: [git]
        pass_filenames: false