title: MiastoX
description: MiastoX - Climb to the Top game on Roblox
url: https://dawju9.github.io
baseurl: /MiastoX
github_username: Dawju9

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - node_modules/
  - .git/
  - Packages/
  - src/
  - scripts/
  - .github/

collections_dir: collections
collections:
  team_members:
    output: false
  projects:
    output: true
  jobs:
    output: true