[package]
name = "MiastoX"
version = "0.1.0"
edition = "2021"

[dependencies]
link = "0.1.1"
lune = "0.8.9"
promise = "0.0.4"
rojo = "7.4.4"
rokit = "0.2.5"
selene = "0.27.1"
stylua = "0.20.0"
wally = "0.3.2"
[dev-dependencies]
wally = "0.3.2"
