[package]
name = "MiastoX"
version = "0.1.0"
edition = "2021"
description = "Projekt gry MiastoX oparty na frameworku Cityx i Rust, obsługujący integrację z .rbxl"
authors = ["Whitekali"]
license = "MIT"
repository = "https://github.com/Dawju9/MiastoX"

[dependencies]
link = "0.1.1" # Biblioteka do łączenia elementów/połączeń
lune = "0.8.9" # Lune - minifikacja, zarządzanie Lua i Lua-Lune skryptami
promise = "0.0.4" # Zarządzanie asynchronicznymi zadaniami
rojo = "7.4.4" # Przekształcanie struktury i synchronizacja
rokit = "0.2.5" # Narzędzia do budowania i pracy nad projektami Lua w Rust
selene = "0.27.1" # Narzędzie do analizy kodu Lua
stylua = "0.20.0" # Formatter Lua
wally = "0.3.2" # Zarządzanie zależnościami w ekosystemie Roblox (produkcja)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
wally = "0.3.2" # Wersja używana do testów i automatyzacji procesu

[build]
# Określ docelowe platformy (np. 64-bitowe oraz 32-bitowe na systemie Linux)
target = ["x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu"]

[game]
# Konfiguracja podstawowych danych gry
citix_config_path = "citix.toml" # Ścieżka do pliku konfiguracyjnego gry
[lib]
name = "MiastoX"
path = "src/lib.rs"
test = true

[[bin]]
name = "MiastoX"
path = "src/main.rs"