[project]
name = "MiastoX"
description = "Modularna gra oparta na frameworku Cityx, zawierająca procedury rozbudowy i testowania"
version = "0.1.0"
author = "Whitekali"
license = "MIT"

[settings]
default_language = "Lua"
base_directory = "src"
entry_point = "main.lua"
assets_directory = "assets"
output_directory = "build"
serialization_format = "rbxl"

[framework]
engine = "Cityx"
engine_version = "1.0.0"
modules_path = "modules"
dependencies_path = "dependencies"
git_repo_url = "https://github.com/Dawju9/MiastoX"

[serialization]
format = "rbxl"
decoded_directory = "decoded"
encoded_directory = "encoded"

[build]
optimization_level = "release"
minify_lua = true
include_assets = true

[testing]
enable_automated_tests = true
test_framework = "Lune"
test_directory = "tests"

[dependencies]
link = "0.1.1"
lune = "0.8.9"
rojo = "7.4.4"
stylua = "0.20.0"
promise = "0.0.4"

[dev-dependencies]
wally = "0.3.2"
selene = "0.27.1"