name: Build and Deploy to Roblox

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger for version tags, like v1.0.0
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Game to Roblox
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Foreman and Rojo
      - name: Download and Install Foreman v1.6.3
        run: |
          curl -sSL https://github.com/Roblox/foreman/releases/download/v1.6.3/foreman-linux.zip -o foreman-linux.zip
          unzip foreman-linux.zip
          sudo mv foreman /usr/local/bin/foreman
          sudo chmod +x /usr/local/bin/foreman
          rm foreman-linux.zip

      # Step 3: Setup Foreman and Install Rojo
      - name: Setup Foreman and Rojo
        run: |
          foreman install

      # Step 4: Verify Rojo installation
      - name: Verify Rojo Installation
        run: |
          rojo --version

      # Step 5: Build the game into .rbxl using Rojo
      - name: Build the game
        run: |
          mkdir -p Temp
          echo "Building ${GITHUB_REF}..."
          rojo build default.project.json --output Temp/CurrentBuild.rbxl

      # Step 6: Create a release on GitHub and upload the build (optional backup)
      - name: Create release and upload build
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./Temp/CurrentBuild.rbxl
          asset_name: Build_${{ github.ref }}.rbxl
          asset_content_type: application/octet-stream

      # Step 7: Deploy to Roblox
      - name: Deploy to Roblox (Production)
        run: |
          echo "Deploying build to Roblox..."
          curl --verbose --location --request POST \
          'https://apis.roblox.com/universes/v1/${{ secrets.TEST_UNIVERSE_ID }}/places/${{ secrets.TEST_PLACE_ID }}/versions?versionType=Published' \
          --header "x-api-key:${{ secrets.API_KEY }}" \
          --header "Content-Type: application/octet-stream" \
          --data-binary @Temp/CurrentBuild.rbxl
        env:
          API_KEY: ${{ secrets.API_KEY }}
