name: Deploy to Staging

on:
  push:
    branches:
    - main
 
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Check file permissions
      run: |
        ls -l ./assets/game.rbxl
    - name: List files in the repository
      run: |
          echo "Listing files to confirm game.rbxl exists:"
          dir  # Adjust this if necessary to match the workflow's working directory
    - name: Check if game.rbxl exists
      run: |
            echo "Current directory: $(pwd)"
            echo "Listing all files in the assets directory:"
            dir F:\EndGames\MiastoX\assets  # Adjust this if the location is different
    - uses: ok-nick/setup-aftman@v0.3.0
      name: Install aftman
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}
    - run: rbxcloud experience publish -f ./assets/game.rbxl -p 11633610328 -u 4125094708 -t published -a ${{ secrets.API_KEY }}
