name: Build and Deploy to Roblox

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger for version tags, like v1.0.0
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Game to Roblox
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Foreman and Rojo using Foreman
      - name: Install Foreman CLI (Zip)
        run: |
          curl -sSL https://github.com/roblox/foreman/releases/download/v0.6.0/foreman-linux-x64.zip -o foreman-linux-x64.zip
          unzip foreman-linux-x64.zip
          sudo mv foreman /usr/local/bin/foreman

      - name: Setup Foreman (Rojo)
        run: |
          foreman install

      # Step 3: Build the game into .rbxl using Rojo (installed via Foreman)
      - name: Build the game
        run: |
          mkdir -p Temp
          echo "Building ${GITHUB_REF}..."
          rojo build default.project.json --output Temp/CurrentBuild.rbxl

      # Step 4: Upload the build to a draft release on GitHub (optional, for backup)
      - name: Create release and upload build
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload build to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./Temp/CurrentBuild.rbxl
          asset_name: Build_${{ github.ref }}.rbxl
          asset_content_type: application/octet-stream

      # Step 5: Deploy to Roblox (using API)
      - name: Deploy to Roblox (Production)
        run: |
          echo "Deploying build to Roblox..."
          curl --verbose --location --request POST \
          'https://apis.roblox.com/universes/v1/${{ secrets.TEST_UNIVERSE_ID }}/places/${{ secrets.TEST_PLACE_ID }}/versions?versionType=Published' \
          --header "x-api-key:${{ secrets.API_KEY }}" \
          --header "Content-Type: application/octet-stream" \
          --data-binary @Temp/CurrentBuild.rbxl
