name: Serialize and Process .rbxl Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  serialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for Lune)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Lune
        run: npm install -g lune

      - name: Run serialization
        run: lune run serialize.lua

      - name: Commit serialized .rbxl files
        run: |
          git config --global user.name 'CI Bot'
          git config --global user.email 'ci-bot@example.com'
          git add game.rbxl
          git commit -m 'Automated serialization of .rbxl files'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}