name: Lua Lint
on:
  push:
    branches: [main]
    paths: [src/**]
  pull_request:
    branches: [main]
    paths: [src/**]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Wally
        run: wally install

      - name: Run Selene
        continue-on-error: true
        run: selene src --config selene.toml

      - name: Check StyLua
        continue-on-error: true
        run: stylua src --check --config stylua.toml
