name: Build and Deploy RBXL Project

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'build.project.json'

jobs:
  build:
    name: Build RBXL Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          if [ ! -d "Packages" ]; then
            sh scripts/install-packages.sh
          fi

      - name: Run Rojo Server and Sourcemap Generation
        run: |
          rojo serve build.project.json &
          rojo sourcemap default.project.json -o sourcemap.json --watch &
          ROBLOX_DEV=true darklua process --config .darklua.json --watch src/ dist/

      - name: Deploy to Roblox
        run: |
          # Dodaj tutaj swoje kroki do deployowania na Roblox
          echo "Deploying to Roblox..."
















          