name: Roblox CI/CD
on:
  push:
    branches:
      - master
    paths:
      - 'encoded/**'
      - 'decoded/**'

jobs:
  deserialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Lua Environment
        uses: leafo/gh-actions-lua@v1
        with:
          lua: "5.1"

      - name: Deserialize .rbxl to decoded structure
        run: lua path/to/your/deserialization_script.lua encoded/myPlaceFile.rbxl decoded/

  serialize:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.paths.include('decoded/**')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Lua Environment
        uses: leafo/gh-actions-lua@v1
        with:
          lua: "5.1"

      - name: Serialize decoded structure to .rbxl
        run: lua path/to/your/serialization_script.lua decoded/ encoded/myPlaceFile.rbxl

      - name: Commit and push changes
        run: |
          git config --local user.email "dawju9@gmail.com"
          git config --local user.name "dawju9"
          git add encoded/
          git commit -m "Auto-update serialized .rbxl files"
          git push
